Repository iMicknl/python-sagemcom-api, pull requests merged in 2024-06, with the labels that each got.

#299 5290 from Frontier
  README.md
Labels: documentation

#312 Improve reboot function and better response validation
  sagemcom_api/client.py
Labels: enhancement

#50 Add method to automatically determine EncryptionMethod to use
  README.md
  sagemcom_api/client.py
  sagemcom_api/const.py
  sagemcom_api/exceptions.py
Labels: feature
